apiVersion: v1
kind: Service
metadata:
 name: media-api-svc
 namespace: dev
spec:
 type: ClusterIP
 selector:
  app: media-api
 ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    #nodePort: 30080