apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      myapp=docker.io/pranjalpohre/k8-dotnetapi
    argocd-image-updater.argoproj.io/myapp.update-strategy: semver
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^1\.\d+\.\d+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  source:
    repoURL: https://github.com/pranjalgit/k8-dotnet.git
    path: k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
